config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'

  resources :events, only: [:index, :new, :show]
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  after_create :new_participant_send

  def new_participant_send
    UserMailer.new_participant_email(self).deliver_now
  end


end

app/models/event.rb
class Event < ApplicationRecord

  # dependance

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :user

  #validation

  validates :start_date, presence: true
  validate :date_cannot_be_in_the_past
  validates :duration, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validate :divisible_by_five

  validates :title, presence: true, length: { in: 3..140 }
  validates :description, presence: true, length: { in: 10..10000 }
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000}
  validates :location, presence: true


  def divisible_by_five
      if (self.duration % 5) != 0
        self.errors[:base] << "Number must be divisible by 5!"
      end
  end

  def date_cannot_be_in_the_past
    if self.start_date.present? && self.start_date < Date.today
      self.errors[:base] << "Date must be in the futur"
    end
  end





end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events
  has_many :attendances
  has_many :events, through: :attendances

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index

  end

  def show

  end

  def new

  end



  def create

  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :user_id_only, only: [:show]


  def show

  end

  private

  def user_id_only
    userid =User.where(email:current_user.email).first
    puts "ICICIC"
    uid =userid.id
    urid = params[:id]
    uid= uid.to_i
    urid= urid.to_i

    if (uid!=urid)
      flash[:error] = "You must be logged in to access this section"
      redirect_to events_path # halts request cycle
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<main role="main">

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="https://images.unsplash.com/photo-1522158637959-30385a09e0da?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Made for</h1>
                <h2>those who do</h2>
                <p><a class="btn btn-lg btn-primary" role="button"<%= link_to "Create now", new_event_path %></a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="https://images.unsplash.com/photo-1454486837617-ce8e1ba5ebfe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1952&q=80" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Made for</h1>
                <h2>those who do</h2>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="https://images.unsplash.com/photo-1556910103-1c02745aae4d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>Made for</h1>
                <h2>those who do</h2>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>


      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
          <%Event.all.each do |event|%>
          <div class="col-lg-4">
            <img class="rounded-circle" src="https://images.unsplash.com/photo-1518495973542-4542c06a5843?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80" alt="Generic placeholder image" width="140" height="140">
            <h2><%=event.title%></h2>
            <p><%=event.description%></p>
            <p><a class="btn btn-secondary" role="button"<%= link_to "View details", event_path(event.id)%></a></p>
          </div><!-- /.col-lg-4 -->
          <%end%>



        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" src="https://images.unsplash.com/photo-1518495973542-4542c06a5843?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5 order-md-1">
            <img class="featurette-image img-fluid mx-auto" src="https://images.unsplash.com/photo-1518495973542-4542c06a5843?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" src="https://images.unsplash.com/photo-1518495973542-4542c06a5843?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

      </div><!-- /.container -->


      <!-- FOOTER -->
      <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>
    </main>

app/views/events/new.html.erb
<h2>Create</h2>

app/views/events/show.html.erb
<% event = Event.find(params[:id])%>

<div class="card">
  <div class="card-header">

  </div>
  <div class="card-body">
    <h5 class="card-title" ><%= event.title%></h5>
    <p class="card-text"><%= event.description%></p>
    <p class="card-text">Price : <%= event.price%></p>
    <a class="btn btn-primary"<%= link_to "Back", events_path %></a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" href="https://www.joinit.org/eventbrite.png">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/carousel/">


    <title>Eventbrit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
   <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
     <a class="navbar-brand" <%= link_to "Eventbrit", events_path%></a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarCollapse">
       <ul class="navbar-nav mr-auto">
         <li class="nav-item active">
           <a class="nav-link" <%= link_to "Create event", new_event_path%><span class="sr-only">(current)</span></a>
         </li>
         <% if user_signed_in? %>

         <li class="nav-item">
           <!-- Example single danger button -->
           <div class="btn-group">
             <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Profil / Sign out
             </button>
             <div class="dropdown-menu">
               <a class="dropdown-item" <%= link_to "Profil", user_path(current_user.id)%></a>
               <a class="dropdown-item" <%= link_to "Sign out", destroy_user_session_path, method: :delete%></a>
             </div>
           </div>

         </li>

         <% else %>
         <li class="nav-item">
           <!-- Example single danger button -->
           <div class="btn-group">
             <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Login / Signup
             </button>
             <div class="dropdown-menu">
               <a class="dropdown-item" <%= link_to "Login", new_user_session_path%></a>
               <a class="dropdown-item" <%= link_to "Signup", new_user_registration_path%></a>
             </div>
           </div>
         </li>

         <% end %>
       </ul>
       <form class="form-inline mt-2 mt-md-0">
         <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
         <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
       </form>
     </div>
   </nav>
 </header>



  <body>


    <%= yield %>
    <!-- Optional JavaScript -->
     <!-- jQuery first, then Popper.js, then Bootstrap JS -->
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   </body>


</html>

app/views/users/show.html.erb
<% user = User.find(current_user.id)%>

<div class="card">
  <div class="card-header">

  </div>
  <div class="card-body">
    <h5 class="card-title" ><%= user.first_name%><%= user.last_name%></h5>
    <p class="card-text"><%= user.description%></p>
    <p class="card-text"><%= user.email%></p>
    <a class="btn btn-primary"<%= link_to "Back", events_path %></a>
  </div>
</div>

<%events= Event.where(user_id: current_user.id)%>
<%events.all.each do |event|%>
<div class="col-lg-4">
  <img class="rounded-circle" src="https://images.unsplash.com/photo-1518495973542-4542c06a5843?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80" alt="Generic placeholder image" width="140" height="140">
  <h2><%=event.title%></h2>
  <p><%=event.description%></p>
  <p><a class="btn btn-secondary" role="button"<%= link_to "View details", event_path(event.id)%></a></p>
</div><!-- /.col-lg-4 -->
<%end%>